version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: inventory-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: inventory_tracker
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - inventory-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: inventory-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - inventory-network

  # Inventory Tracker Application
  app:
    build: .
    container_name: inventory-tracker
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/inventory_tracker?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_change_in_production
      CLIENT_URL: http://localhost:3000
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@gmail.com
      EMAIL_PASS: your_app_password
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server/uploads:/app/server/uploads
    networks:
      - inventory-network

volumes:
  mongodb_data:

networks:
  inventory-network:
    driver: bridge
